### ISSUE TITLE
MMDが起動できなくなる不具合

### ISSUE THREAD

**Issue by mf-Mii** [PTOM76/MMDDiscordRPC#1]
記述通りにプラグインをインストールするとMMDが起動できなくなる不具合が発生しました。

**環境**
OS: Windows10 21H2
MMD: v9.32(64bit)
Plugins: MMDUtility, MMEffect, Effekseer, MMAccess, MMDPlugin, MMPlus(S), MMDDiscordRPC

**状況**
MMDを起動しても画面が表示されない

**Comment by PTOM76** [comment]
一旦MMDDiscordRPCを抜いて起動し、再度MMDDiscordRPCを入れると起動できることがあります。
また、MMDUtilityとMMPlusに互換を持たせるために修正したものもあるのでもしかしたらこちらで治るかもしれません。
https://github.com/PTOM76/MMDUtility
